version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "8080:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:

